# Welcome to Jekyll!
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Netscylla's Blog
email: enquiry@netscylla.com
description: >- # this means to ignore newlines until "baseurl:"
  Interesting thoughts and opinions from the field of cyber security in general, focusing mainly on penetration testing and red-teaming, with the occasional perspective from blue-teaming and DevSecOps.
baseurl: "/blog" 
siteurl: "https://www.netscylla.com"
host: "www.netscylla.com"
port: 80
url: "https://www.netscylla.com"
twitter_username: netscylla
github_username:  netscylla
facebook_username: netscylla
google_analytics: UA-28179097-2
environment: production

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
